---
name: 'helm-docs'

description: 'Generate helm readme and changelogs, commit, then push'

runs:
  using: 'composite'
  steps:
    - name: Execute helm-docs to generate READMEs
      shell: bash
      run: |
        helm-docs

    - name: Run helm-changelog
      shell: bash
      run: helm-changelog -v info

    - name: Commit generated README.md
      shell: bash
      run: |
        for chart in $(cat charts-changed.txt) ; do
          echo "=== $chart"
          git add $chart/README.md
        done

    - name: Commit generated Changelog.md
      shell: bash
      run: |
        for chart in $(cat charts-changed.txt) ; do
          echo "=== $chart"
          git add $chart/Changelog.md
        done

    - name: Commit generated docs
      shell: bash
      run: |
        if [ -n "$(git diff --name-only --cached | egrep 'README.md|Changelog.md')" ] ; then
          git commit -a -m 'feat(helm-docs): Update generated helm docs [skip ci]'
        fi

    - name: Push changes
      shell: bash
      run: git push